// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzuaiolxjuxqzxaipqtd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6dWFpb2x4anV4cXp4YWlwcXRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NjA0NTUsImV4cCI6MjA2NzUzNjQ1NX0.CGhjrTKk2iB3A18UjP3b3FPhF0e2Zt7C9SenpMT5MvY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});